### PR TITLE
VPRAB-3842: use newer graphql-tools dependency

### PR DESCRIPTION
**Pull request by logovaser**
https://jira.expedia.biz/browse/VPRAB-3842

### :pencil: Description
Resolves dependabot issue

### CODE REVIEW

**Comment by stigsell** [comment]
I have verified on my computer that this component can be built and works as expected in our `polaris-api-federated-server` project. I approve this PR.

**Comment by stigsell** [comment]
@tlivings could you please review this PR when you get a chance? We get dependabot alerts because of this dependency, so we would like to make the fix to prevent future alerts. 

Thanks,
Nick Stigsell
PM Rates team - Escapia
nstigsell@expediagroup.com

**Review by tlivings — APPROVED** [review]
Looks good to me. @brianjquinn can you take a look too and merge/release if good? On vacation and on a phone 😄

**Comment by HananeMoshe** [comment]
Thank you for jumping on this, I know you are on vacation Trevor. @brianjquinn when you get to this, is there any manual changelog that we need to update for this change? If so, let us know and we will take care of it. Thank you!

**Review by HananeMoshe — APPROVED** [review]
LGTM 👍

**Comment by tlivings** [comment]
To release we need to bump minor version and then tag a release.

**Comment by HananeMoshe** [comment]
> To release we need to bump minor version and then tag a release.

@logovaser @stigsell can one of you take care of this when you have some time. Thank you Trevor.

**Comment by logovaser** [comment]
I don't have merging access

**Pull request merged**
