### PR TITLE
Update index.d.ts to fix the issue with ES6 syntax

### PR DESCRIPTION
**Pull request by yanpingcheng**
1. Add any for Promise.
2. export default GraphQLComponent

### CODE REVIEW

**Comment by tlivings** [comment]
Sorry, some updates have occurred. Please resolve conflicts.

**Comment by brianjquinn** [comment]
I think as @tlivings communicated in an email - the index.d.ts file was inadvertently deleted in the latest master commits ... @yanpingcheng if you checkout the `v1.x` branch and open a PR with your changes to `index.d.ts` against that branch instead of master - we will be able to merge your change and publish the fix

**Comment by brianjquinn** [comment]
@yanpingcheng - you still need to resolve the conflict (since the index.d.ts file was accidentally deleted on the master branch) ... also since master is our working 2.0.0 branch you would want to add the static `delegateToComponent` function to the index.d.ts file

**Comment by brianjquinn** [comment]
closing this due to: https://github.com/ExpediaGroup/graphql-component/pull/66

**Pull request closed without merging**
